### ISSUE TITLE
Migration of Survey Pluging for Confluence to SharePoint 2013

### ISSUE THREAD

**Issue by MikeTTa** [drohne1673/confluence-survey-plugin#63]
all,

We are migrating from Confluence to SharePoint 2013. We have many plugins such as this Survey plugin for Confluence. We want to know two things:

- Can we get to the content of this plugin using an API? Meaning does this expose its content through API?

- What is the migration story to move the content of this to SharePoint?

Thanks

**Comment by drohne1673** [comment]
There are REST resources which this plugin uses via ajax calls. I cant really tell if you can access them without the context the plugin runs in.

The actual data is stored in the properties of the page the macro runs in, see the DB Section for that: https://github.com/drohne1673/confluence-survey-plugin/wiki/Database-modifications

maybe that helps

**Comment by drohne1673** [comment]
is there anything i can help here? Please reopen if you feel i can help you somehow
