### ISSUE TITLE
Vote macro when accessing as anonymous user

### ISSUE THREAD

**Issue by KarthikYS** [drohne1673/confluence-survey-plugin#66]
Currently, below message appears in the vote macro column, when accessing the Confluence page as anonymous:

Error rendering macro 'vote' : parameter name must not be empty!

Is it possible to change the message to something more meaningful.

Thanks & Regards,

**Comment by drohne1673** [comment]
I will check when i am at home if there can be done something, but i guess it is the default given by confluence for a mandatory field.

But the title of the macro is not bound to a user, so there should not be a difference between anonymous and logged in users. So i guess we have to differenciate here:

* How did you create the macro? Via the macro-editor i guess? There you should have been told that the field is mandatory.
* I will change the title of this question to something like "message of mandatory field should be improved"

**Comment by drohne1673** [comment]
Hi, i just checked trying to work around the mandatory fields. I can insert a vote macro with a invalid character and it then gets rendered like:

![bildschirmfoto 2015-03-01 um 22 00 30](https://cloud.githubusercontent.com/assets/1702067/6432789/76edd14c-c05e-11e4-8b94-c4c3808d825d.png)

Can you give me a little bit more information on your settings? Is the mentioned vote macro working for none anonymous users?

**Comment by KarthikYS** [comment]
Hi, Yes, it perfectly works fine for non-anonymous users. We get this "error rendering" message only when we access the page anonymously.

Sorry if i'm misleading you, let me explain you the scenario again:

* Login to Confluence
* insert the vote macro in the Confluence page (works)
* All logged in users can access the page and vote as usual (Works)
* When anonymous users try to access the page, whole content is displayed as expected but the vote macro column is replaced with the below message:

*Error rendering macro 'vote' : parameter name must not be empty!*

**Comment by drohne1673** [comment]
Is it possible that your plugin version is older than 2.8.4, as the anonymous user support has been fixed there (see #48) ?

**Comment by KarthikYS** [comment]
Ok, we are still at version: 2.8.1

That helps...thanks a lot

**Comment by drohne1673** [comment]
ok, thanks for the clarification.

Please update the plugin ;)

**Comment by vishenabhisheksingh** [comment]
Hello,
Is it possible that anonymous user can vote on survey?

Regards, 
Abhi

**Comment by drohne1673** [comment]
no, anonymous can only view results but cannot vote.
