### ISSUE TITLE
/rest/surveyplugin/1.0/pages/[clientID]/votes make error "There was a problem casting a vote. Returned status: error, error: Unauthorized" on Safari

### ISSUE THREAD

**Issue by wanybae** [drohne1673/confluence-survey-plugin#67]
When I try this(vote) on Chrome, it work.
But on Safari, popup alert said
 "There was a problem casting a vote. Returned status: error, error: Unauthorized" 

It make cannot vote on Safari.

**Comment by drohne1673** [comment]
I have no problem using this with Safari. So lets try to verify your environment.

I go to <confluence>/display/SRV/mySurvey and vote with both browsers. I have Safari 8.0.2, confluence 5.7 and the latest survey plugin. The confluence base url is identical and i am logged in.

Can you describe it similarly?

**Comment by drohne1673** [comment]
24 days without new insights. Feel free to reopen if there is new info. I cant test all environments if that may be an issue

**Comment by wanybae** [comment]
I am so sorry, I didn't realise you comment.
I will double check this issue. 
