### ISSUE TITLE
possible memory leak?

### ISSUE THREAD

**Issue by malcook** [drohne1673/confluence-survey-plugin#70]
Hi,

I installed this macro on our development confluence server on 3/28/15 10:11am 

Our admin thinks this may have introduced a memory leak, and reported

"(the server) only had 12% java heap memory available. Upon disabling new addon I was back to 30% available memory. Before we enable this add-on (in our production server), I'll need to increase memory on java/OS and investigate memory leak."

Do you have any knowledge of how this might be possible or how best to isolate the possible impact of the macro on our server and report it to you?

Thanks

**Comment by drohne1673** [comment]
I doubt that.

I just did that same test. Started with a enabled Plugin. 289MB free, disabled it, the free java heap gone up to 367. Enabled again went up again to 512.

The plugin does nothing without interaction and it is very lightweight. So by just enabling, disabling it it may be that some classes are loaded but no code is run at that point. You have to actively move to a page with that macro to use some memory.

Memory leaks can be analyzed with tools like jprofiler. Without such tools i would think that having a basic installation without 3rd party plugins and then enabling one by one is probably the best way to see how they behave.

Is there just this one time impression? Or have you tried it several times? The code base has improved a lot and its there almost 10 years now. But nothing is curtain of course ;)

**Comment by malcook** [comment]
Hi - Thanks for quick reply.  My statement of the issue was not clear.
 I did not only install the macro - I also used the macro and set up a test
survey.  And, I immediately thereafter took the survey and asked a few
other people to take the survey.

So there was really no way to ascribe the memory issue to simply
installation.

I will try and get the admin to coordinate with me and run a more
controlled test on this macro.

Thanks for your thoughts.

~Malcolm

**Comment by drohne1673** [comment]
i also asked some collegues, there are some memory analyzers, where a memory dump of the jvm can be analyzed. If you are on that track already i would be happy to get your feedback. I will close this issue until you think you can point more concrete that this plugin is troubling you
