### ISSUE TITLE
Finding Results

### ISSUE THREAD

**Issue by Jbissell89** [drohne1673/confluence-survey-plugin#73]
How do I find the results of the survey

**Comment by drohne1673** [comment]
Data is stored in the properties of the wiki pages, there are some sql statements for removing and updating datain the wiki https://github.com/drohne1673/confluence-survey-plugin/wiki/Database-modifications.

Is that what you are looking for?

**Comment by Jbissell89** [comment]
![list of viewers](https://cloud.githubusercontent.com/assets/11934029/7138389/f965a54a-e274-11e4-9dca-1f620f08545a.JPG)

The "list of viewer" option is selected, by the results of the survey do not populate?

**Comment by drohne1673** [comment]
The list which are designed for user and group names, only allow the user key and not the full name. So in your case probably something like `jbissel`. As there currently is no GUI for selecting the users, the best way to maintain this are group-names, like `confluence-users` or `confluence-administrators` (the two default groups of confluence)

**Comment by Jbissell89** [comment]
I tried Jbissell... no luck.

**Comment by drohne1673** [comment]
FYI: these lists restrict the usage. So, if the field is empty you should be able to see the results right away

**Comment by drohne1673** [comment]
Is `Jbissell` your use key?

**Comment by Jbissell89** [comment]
I believe Jbissell is my key how do I locate the key source?

**Comment by Jbissell89** [comment]
Also I am apart of a Group I can give access to this group, is there a way to locate the Group Key?

**Comment by drohne1673** [comment]
i am on holiday right now. Your username should show up if you hover over your name, something like this https://confluence.atlassian.com/display/DOC/User+Profile+Macro. The username is your unique key in confluence, where your full name not necesserily is unique.

**Comment by drohne1673** [comment]
if your confluence version is not too old you should see such thing like your groups in your profile (upper right corner)

**Comment by Jbissell89** [comment]
![pic](https://cloud.githubusercontent.com/assets/11934029/7144028/96c0a6ec-e297-11e4-82c0-949df5100127.JPG)

This is what I see

**Comment by Jbissell89** [comment]
I was doing Jbissell it is jbissell!

**Comment by Jbissell89** [comment]
Is there a way to have the results exported to another page?

**Comment by drohne1673** [comment]
yes, sorry, it is case sensitive. 

There is a export as a csv file. You have to use the `survey` plugin for getting the menu bar in the survey.

**Comment by Jbissell89** [comment]
Great Thank you! Case Closed, Mission accomplished
