### ISSUE TITLE
where are votes stored in confluence database

### ISSUE THREAD

**Issue by ingohackl** [drohne1673/confluence-survey-plugin#76]
Hi,

we want to export the votes from confluence database into an xml-file to transfer them to answerhub.

Where in the confluence database (which table and which field) are the votes stored?

Ingo

**Comment by drohne1673** [comment]
The questions are stored as properties, directly at the wiki pages. Hints on how to retrieve via SQL can be found in the wiki: https://github.com/drohne1673/confluence-survey-plugin/wiki/Database-modifications

Currently there is only a CSV export available on each single survey macro, otherwise. 

Feel free to reopen this issue if you need further assistance

**Comment by ingohackl** [comment]
To get the votes for a page I could use following query: select * from OS_PROPERTYENTRY where entity_id = 122717162 and entity_key like 'vote.%';

Am I right for this? Because I don't get any results although the page has 34 votes on it.

**Comment by drohne1673** [comment]
When i do that with a postgresql database i get the following data and a page with id 720900. The voters are stored in the text_val column. So in my purpose just the user `admin` voted.

"confluence_ContentEntityObject";720900;"vote.tralala.3-Satisfactory";6;f;0;"";"";0;0;""
"confluence_ContentEntityObject";720900;"vote.tralala.4-More Than Satisfactory";6;f;0;"";"";0;0;""
"confluence_ContentEntityObject";720900;"vote.tralala.5-Outstanding";6;f;0;"";"";0;0;""
"confluence_ContentEntityObject";720900;"vote.tralala.2-Less Than Satisfactory";6;f;0;"";"admin";0;0;""


What type of database are you using? The entity_id is your page_id right? I currently use hsql, i only had that postgresql database for my cluster tests, so i dont have much data to play around. Does that help you?

**Comment by drohne1673** [comment]
I added the select statement and this result to the mentioned wiki page now
