### ISSUE TITLE
Always Show Results option not working in Vote macro

### ISSUE THREAD

**Issue by aviramga** [drohne1673/confluence-survey-plugin#77]
Hi,
I noticed that in Confluence 5.7.3 the Always Show Results in the Vote macro isn't working.
Steps to recreate:
1. Create 2 Users, userA and userB.
2. Login as userA and create a vote with the Vote macro, add at least 2 options and check the Always Show Results checkbox.
3. Cast a vote with userA.
4. Login with userB and go to the vote page.

The results will not appear for userB, only after he casts a vote.
Please advise.

Thanks!

**Comment by drohne1673** [comment]
These are just sample names, are they? as a user key only lowercase is allowed

**Comment by drohne1673** [comment]
works fine for me. Having Confluence 5.7. I will try 5.7.3 now.

**Comment by drohne1673** [comment]
I have updated to 5.7.3 and created a `survey` and a `vote` as user `admin`. I voted on the `vote`-macro (located beneath the `survey`-macro where i didnt vote). I then logged in as the user `jdoe`and made the screenshot. Looks quite well, doesnt it? 

![bildschirmfoto 2015-04-28 um 23 59 10](https://cloud.githubusercontent.com/assets/1702067/7381333/a51c754c-ee02-11e4-9f9f-a49038743bc7.png)

Can you do the same?

**Comment by aviramga** [comment]
Hi, Yes these were just sample names.
Also, it doesnt work for me and the design is a bit different, in my macros instead of the empty checkboxes there is a blue circle with a V in it, which turns green when I vote. Could it be we are running different versions?

Here is my plugin manager screeshot:
![survey](https://cloud.githubusercontent.com/assets/4211506/7385780/1428226e-ee54-11e4-9193-cb26c2711407.png)

**Comment by drohne1673** [comment]
Ahoi,

it seems you are using this plugin since some time. The plugin with version 1.2.0 is at least 3 years old. Please uninstall this old version and try to use the `vote`macro again. It is always a good thing to have only one plugin of one kind installed (unique key).

Actually it is unusual that you were able to install two versions, i knew this behavior only in older confluence installations older than 3.0, where the plugins were installed manually sometimes.

Does this help?
--Frank

**Comment by aviramga** [comment]
That worked! I thought there was 2 parts to the plugin and needed both. That fixed it, strange it just didnt update with confluence.
Thanks a lot!!

**Comment by drohne1673** [comment]
All modules needed in most of the plugins are named in the right column `25 of 25 modules enabled`. I am curtain that plugins with the same name should only exist once in the system, until someone did not name their plugin uniquely.

Glad we could resolve this ;)
