### ISSUE TITLE
Issue with survey plugin

### ISSUE THREAD

**Issue by vishenabhisheksingh** [drohne1673/confluence-survey-plugin#78]
Hello,

I am facing issue with survey and vote macro. As admin when I login on my system I am able to vote where as when i login in other browser as a user in my system still I able to vote but when I am login from other system as a user or admin I am not able to vote. There i error showing bad request error. 

Regards,
Abhishek

**Comment by drohne1673** [comment]
Hi Abhishek,

that is only possible when you are accessing the system via different URI's. Atlassian's system usually depends on the configured base URL. If the configured url mismatches the url you are using that bad request may occur.

Hope that helps
--Frank
